apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskrest-deployment
  labels:
    app: flaskrest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskrest
  template:
    metadata:
      labels:
        app: flaskrest
    spec:
      containers:
      - name: flaskrest
        image: dockeruseranu123/pythonapp:latest
        ports:
        - containerPort: 8100

#
## Servcie type loadbalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: my-service
#spec:
#  selector:
#    app: flaskrest
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8100
#  type: LoadBalancer